name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Code Quality (PHPCS & PHPStan)
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, hash, json, pcre, session, tokenizer, zip
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,yml --ignore=node_modules,bower_components,vendor web/modules/custom web/themes/custom

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level 6 web/modules/custom web/themes/custom

  unit-tests:
    name: PHPUnit Unit Tests
    runs-on: ubuntu-24.04
    if: github.event_name != 'push'
    # Excluding here because unit tests are included in full suite

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, hash, json, pcre, session, tokenizer, zip
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit unit tests
        run: vendor/bin/phpunit -c web/core/phpunit.xml.dist web/modules/custom/*/src/tests/Unit --testsuite unit --stop-on-error --stop-on-fail --testdox

  filesystem-security-scan:
    name: Filesystem Security Scan
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'

  accessibility-tests:
    name: Accessibility Tests
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: drupal
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, pdo_sqlite, dom, filter, gd, hash, json, pcre, session, tokenizer, zip
          coverage: none
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install pa11y
        run: npm install -g pa11y

      - name: Install Drupal
        run: |
          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "\$databases['default']['default'] = [
            'database' => 'drupal',
            'username' => 'root',
            'password' => 'drupal',
            'prefix' => '',
            'host' => '127.0.0.1',
            'port' => '3306',
            'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
            'driver' => 'mysql',
          ];" >> web/sites/default/settings.php
          vendor/bin/drush site:install standard --db-url=mysql://root:drupal@127.0.0.1:3306/drupal --yes

      - name: Start PHP server
        run: |
          php -S 127.0.0.1:8080 -t web &
          sleep 10

      - name: Run pa11y accessibility tests
        run: |
          echo "Running accessibility tests..."
          # Allow pa11y to pass even with violations - fresh Drupal installs often have
          # accessibility issues in core themes that developers cannot immediately fix
          pa11y http://127.0.0.1:8080 --standard WCAG2AA --reporter cli || true
          pa11y http://127.0.0.1:8080/user/login --standard WCAG2AA --reporter cli || true
          pa11y http://127.0.0.1:8080/user/register --standard WCAG2AA --reporter cli || true

  # Additional jobs that only run on merge (push) to develop/main
  full-tests:
    name: PHPUnit - All Test Suites (requires db)
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    needs: [static-analysis, filesystem-security-scan]

    permissions:
      contents: read
      actions: read
      checks: write

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: drupal
          MYSQL_DATABASE: drupal
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, pdo_sqlite, dom, filter, gd, hash, json, pcre, session, tokenizer, zip
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install Drupal
        run: |
          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "\$databases['default']['default'] = [
            'database' => 'drupal',
            'username' => 'root',
            'password' => 'drupal',
            'prefix' => '',
            'host' => '127.0.0.1',
            'port' => '3306',
            'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
            'driver' => 'mysql',
          ];" >> web/sites/default/settings.php
          vendor/bin/drush site:install standard --db-url=mysql://root:drupal@127.0.0.1:3306/drupal --yes

      - name: Run PHPUnit full test suite
        env:
          SIMPLETEST_BASE_URL: http://127.0.0.1:8080
          SIMPLETEST_DB: mysql://root:drupal@127.0.0.1:3306/drupal
        run: |
          php -S 127.0.0.1:8080 -t web &
          sleep 5
          mkdir -p build/logs
          vendor/bin/phpunit -c web/core/phpunit.xml.dist web/modules/custom/ --log-junit=build/logs/phpunit.junit.xml --stop-on-error --stop-on-fail

      - name: Report test results to GitHub
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: PHPUnit Test Results
          path: build/logs/phpunit.junit.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: true
          list-suites: failed
          list-tests: failed
          max-annotations: 10
          use-actions-summary: true

  docker-security-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    needs: [static-analysis, full-tests, filesystem-security-scan]

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: arsapps:security-scan
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy image vulnerability scanner (Table format)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'arsapps:security-scan'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Run Trivy image vulnerability scanner (SARIF format)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'arsapps:security-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      # Reenable after fixing PAT token issue
      # - name: Upload Trivy scan results to GitHub Security
      #   uses: github/codeql-action/upload-sarif@v3
      #   if: always()
      #   with:
      #     sarif_file: 'trivy-results.sarif'
